rook-ceph:
  images:
    rook:
      repository: rook/ceph
      tag: v1.2.4
      pullPolicy: IfNotPresent
    ceph:
      repository: ceph/ceph
      tag: v14.2.6
      pullPolicy: IfNotPresent
    hyperkube:
      repository: k8s.gcr.io/hyperkube
      tag: v1.12.1
      pullPolicy: IfNotPresent
  mon:
    count: 1
  filesystem:
    metaReplicas: 1
    dataReplicas: 1
    reclaimPolicy: Delete
  blockstorage:
    replicas: 1
    reclaimPolicy: Delete
  nodes:
    - hostname: minikube
      directories:
      - path: /mnt/sda1/var/lib/rook
cdi:
  verbosity: 1
  images:
    cdi:
      repositoryPrefix: kubevirt
      tag: v1.13.0
      pullPolicy: IfNotPresent
    hyperkube:
      repository: k8s.gcr.io/hyperkube
      tag: v1.12.1
      pullPolicy: IfNotPresent
